GET http://localhost:3000

####

POST http://localhost:3000/addDriver
Content-Type: application/json

{
	"_id": "199",
	"name": "John",
	"carMake": "Maruti",
	"lat": "150",
	"long": "50"
}

####

GET http://localhost:3000/getDriverBy_id
Content-Type: application/json

{
	"_id": "99"
}

####

GET http://localhost:3000/getCloseDrivers
Content-Type: application/json

{
	"name": "test user",
	"lat": "150",
	"long": "50"
}
